### ISSUE TITLE
Trim leading zeroes when displaying times

### ISSUE THREAD

**Issue by rickygv99** [stanford-oval/thingtalk#141] opened 2019-09-03 19:50 UTC
Right now, Almond displays times with leading zeroes (e.g. 09:00). It would be more user-friendly to trim leading zeroes when displaying times to the user (e.g. 9:00).

**Comment by gcampax** [comment] 2019-09-03 21:12
Duplicate of #140

**Closed by gcampax** 2019-09-03 21:12 UTC
